import os
import torch
import gradio as gr
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from peft import PeftModel
from huggingface_hub import snapshot_download

try:
    from langdetect import detect as _detect
    def detect_language(text):
        try:
            lang = _detect(text)
            return lang if lang in SUPPORTED_LANGS else "en"
        except Exception:
            return "en"
except ImportError:
    def detect_language(text):
        return "en"

# ── Config ───────────────────────────────────────────────────────────────────
MODEL_REPO   = "ahmedkilani/xDetect-multilingual-detector"
BACKBONE_DIR = "backbone/xlmr_base"
ADAPTERS     = {"de": "adapters/de_full", "ar": "adapters/ar_full"}
SUPPORTED_LANGS = {"en", "de", "ar"}
LANG_NAMES   = {"en": "English", "de": "German", "ar": "Arabic"}
MAX_LENGTH   = 512
DEVICE       = "cuda" if torch.cuda.is_available() else "cpu"

# ── Download model files once ────────────────────────────────────────────────
print("Downloading model files...")
local_dir     = snapshot_download(repo_id=MODEL_REPO)
BACKBONE_PATH = os.path.join(local_dir, BACKBONE_DIR)
ADAPTER_PATHS = {lang: os.path.join(local_dir, path) for lang, path in ADAPTERS.items()}
print(f"Cached at: {local_dir}")

tokenizer = AutoTokenizer.from_pretrained(BACKBONE_PATH, local_files_only=True)
_model_cache = {}

def get_model(lang):
    if lang in _model_cache:
        return _model_cache[lang]
    base = AutoModelForSequenceClassification.from_pretrained(
        BACKBONE_PATH, num_labels=2, local_files_only=True
    ).to(DEVICE)
    if lang in ADAPTER_PATHS and os.path.exists(ADAPTER_PATHS[lang]):
        model = PeftModel.from_pretrained(base, ADAPTER_PATHS[lang], local_files_only=True).to(DEVICE)
    else:
        model = base
    model.eval()
    _model_cache[lang] = model
    return model

# ── Inference ────────────────────────────────────────────────────────────────
def predict(text, language_override):
    if not text or not text.strip():
        return "⚠️ Please enter some text.", "", ""

    if language_override == "Auto-detect":
        lang = detect_language(text)
        lang_display = f"{LANG_NAMES.get(lang, lang)} (auto-detected)"
    else:
        lang = {"English": "en", "German": "de", "Arabic": "ar"}[language_override]
        lang_display = LANG_NAMES[lang]

    inputs = tokenizer(
        text, return_tensors="pt", truncation=True,
        max_length=MAX_LENGTH, padding=True
    ).to(DEVICE)

    with torch.no_grad():
        logits = get_model(lang)(**inputs).logits
    TEMPERATURE = 3.0  # calibration: spread overconfident probabilities
    probs = torch.softmax(logits / TEMPERATURE, dim=-1)[0]

    p_human   = probs[0].item()
    p_machine = probs[1].item()
    confidence = max(p_human, p_machine)

    # Calibrated verdict — avoid binary 100% claims
    if p_machine > p_human:
        if confidence > 0.95:
            verdict = "🤖 Very likely MACHINE-GENERATED"
        elif confidence > 0.75:
            verdict = "🤖 Probably MACHINE-GENERATED"
        else:
            verdict = "⚠️ Uncertain — leaning machine"
    else:
        if confidence > 0.95:
            verdict = "✍️ Very likely HUMAN-WRITTEN"
        elif confidence > 0.75:
            verdict = "✍️ Probably HUMAN-WRITTEN"
        else:
            verdict = "⚠️ Uncertain — leaning human"

    adapter_used = "de_full" if lang == "de" else "ar_full" if lang == "ar" else "none (zero-shot)"

    detail = (
        f"**Language:** {lang_display}  \n"
        f"**Human probability:** {p_human:.1%}  \n"
        f"**Machine probability:** {p_machine:.1%}  \n"
        f"**Confidence:** {confidence:.1%}  \n\n"
        f"*Backbone: XLM-R-base · Adapter: {adapter_used} · Device: {DEVICE.upper()}*"
    )

    return verdict, detail, ""

# ── UI ───────────────────────────────────────────────────────────────────────
DESCRIPTION = """
## xDetect — Multilingual AI-Generated Text Detector

Detects whether text was written by a human or generated by an AI in **English**, **German**, and **Arabic**.

**Architecture:** XLM-R-base backbone (270M params) + LoRA adapters for German and Arabic  
**Trained on:** [MultiTuDe v3](https://huggingface.co/ahmedkilani/xDetect-multilingual-detector) — news/summarization domain  
**⚠️ Scope:** Trained on news/summarization text (MultiTuDe v3). Best used for detecting AI-generated news articles and summaries. Well-structured formal text — whether human or machine — may score similarly; this is a known limitation of statistical detection methods (Liang et al., 2023). Not validated for informal, social media, or academic writing.  
**Code:** [github.com/Med-Ahmed-Kilani/xDetect](https://github.com/Med-Ahmed-Kilani/xDetect) · *TEK-UP Graduation Thesis, 2026*
"""

EXAMPLES = [
    ["The implementation of advanced neural network architectures has significantly enhanced the capabilities of modern natural language processing systems, enabling more sophisticated understanding of contextual semantics.", "English"],
    ["Floods hit southern regions after days of heavy rainfall, displacing thousands of residents. Emergency services were deployed overnight and local authorities urged people to avoid low-lying areas.", "English"],
    ["Die Klimakrise erfordert sofortige Maßnahmen auf globaler Ebene, da die Temperaturen weltweit weiter ansteigen und die Folgen für Mensch und Natur immer gravierender werden.", "German"],
    ["يُعدّ الذكاء الاصطناعي من أبرز التقنيات التي شهدها العالم في العقود الأخيرة، إذ أحدث ثورة حقيقية في مختلف المجالات الحياتية.", "Arabic"],
]

with gr.Blocks(title="xDetect — AI Text Detector", theme=gr.themes.Soft()) as demo:
    gr.Markdown(DESCRIPTION)

    with gr.Row():
        with gr.Column(scale=3):
            text_input = gr.Textbox(
                label="Input Text",
                placeholder="Paste news or article text here (English, German, or Arabic)...",
                lines=8,
            )
            lang_choice = gr.Radio(
                choices=["Auto-detect", "English", "German", "Arabic"],
                value="Auto-detect",
                label="Language",
            )
            submit_btn = gr.Button("🔍 Detect", variant="primary", size="lg")

        with gr.Column(scale=2):
            verdict_out = gr.Markdown(label="Verdict", value="")
            detail_out  = gr.Markdown(label="Details", value="")
            _hidden     = gr.Markdown(visible=False)

    gr.Examples(examples=EXAMPLES, inputs=[text_input, lang_choice], label="Example texts")

    submit_btn.click(predict, [text_input, lang_choice], [verdict_out, detail_out, _hidden])
    text_input.submit(predict, [text_input, lang_choice], [verdict_out, detail_out, _hidden])

demo.launch()