[project]
name = "climate-change"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "cdsapi>=0.7.7",
    "cfgrib>=0.9.15.1",
    "dask[complete]>=2026.7.1",
    "datasets>=5.0.1",
    "django>=6.0.8",
    "earthaccess>=0.18.0",
    "earthengine-api>=1.7.38",
    "eccodes>=2.47.0",
    "geemap>=0.38.3",
    "h5netcdf>=1.8.1",
    "h5py>=3.16.0",
    "ipykernel>=7.3.0",
    "netcdf4>=1.7.4",
    "pandas-stubs~=3.0.5",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "xarray>=2026.7.0",
]
