dataset: ruler
data_dir: 4096
model: meta-llama/Llama-3.1-8B-Instruct
device: cuda:0
press_name: RestoreKV
compression_ratio: 0.9375
key_channel_compression_ratio: null
restore_checkpoint: higokri/RestoreKV/llama3.1-8b_restorekv.pt
fraction: 1.0
max_new_tokens: null
max_context_length: null
query_aware: false
needle_depth: null
compression_interval: null
target_size: null
hidden_states_buffer_size: null
output_dir: ./results_lb
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
press_init_command: RestoreKVPress(compression_ratio=0.9375, layerwise=False, n_sink=4,
  kvzip_plus_normalization=False, checkpoint_path='higokri/RestoreKV/llama3.1-8b_restorekv.pt',
  budget_matched=True)
seed: 42
fp8: false
