services:
  - type: web
    name: vet-insilico-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.render
    healthCheckPath: /api/health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
