dataset: ruler
data_dir: 4096
model: Qwen/Qwen3-8B
device: cuda:3
press_name: adakv_compactor
compression_ratio: 0.875
key_channel_compression_ratio: null
threshold: null
fraction: 1.0
max_new_tokens: null
max_context_length: null
query_aware: false
needle_depth: null
compression_interval: null
target_size: null
hidden_states_buffer_size: null
output_dir: ./results_lb
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
press_init_command: AdaKVPress(press=CompactorPress(compression_ratio=0.875, sink_size_start=8,
  sink_size_end=4, chunk_size=256, sketch_dimension=48, blending=None, _leverage_press=LeverageScorePress(compression_ratio=0.875,
  sketch_dimension=48), _non_causal_press=NonCausalAttnPress(compression_ratio=0.875,
  chunk_size=256)), alpha_safeguard=0.2)
seed: 42
