# config.py

SPREADSHEET_NAME = "Vocabulary Analysis System"

ESSAY_SHEET = "Essay"
POS_SHEET = "POS"
DEP_SHEET = "DEP"
GRAMMAR_SHEET = "Grammar"
VOCAB_SHEET = "Vocabulary"

GOOGLE_SECRET_NAME = "GOOGLE_SERVICE_ACCOUNT_JSON"
HANLP_SECRET_NAME = "HANLP_AUTH"