[supervisord]
nodaemon=true

[program:django]
command=bash -c "cd backend && python manage.py migrate && exec python manage.py runserver 0.0.0.0:7860 --insecure"
autostart=true
autorestart=true
stopsignal=TERM
stopwaitsecs=10
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:whatsappbot]
command=bash -c "cd whatsapp_bot && exec node bot.js"
autostart=true
autorestart=unexpected
stopsignal=TERM
stopwaitsecs=30
startsecs=30
startretries=10
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
