# Generated by Django 6.0.4 on 2026-05-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_userprofile_last_expense_date_userprofile_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
        ),
    ]
