# Generated by Django 6.0.7 on 2026-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
