# Generated by Django 6.0.7 on 2026-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_userprofile_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='budget_cycle_start_day',
            field=models.IntegerField(default=1),
        ),
    ]
