dataset: ruler
data_dir: 4096
model: Qwen/Qwen3-8B
device: cuda:0
press_name: cur
compression_ratio: 0.25
key_channel_compression_ratio: null
threshold: null
fraction: 1.0
max_new_tokens: null
max_context_length: null
query_aware: false
needle_depth: null
compression_interval: null
target_size: null
hidden_states_buffer_size: null
output_dir: ./results_lb
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
press_init_command: CURPress(compression_ratio=0.25, num_sinks=4, leverage_type='kv_product',
  use_random_leverage=False, use_local_approximation=True, local_window_size=16)
seed: 42
