use_default_settings: true

general:
  instance_name: "SearXNG Verifier"

server:
  limiter: false
  secret_key: "f0b7e99a9d5f5201be5f7dfe1f4d0156e0fad85e28918fccba0cc1ccf71af85e"
  bind_address: "0.0.0.0"
  port: 7860

search:
  formats:
    - html
    - json
