"""initial_schema

Revision ID: 25a080f739da
Revises: 
Create Date: 2026-05-10 13:06:45.004308+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25a080f739da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Agent名称'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='角色类型'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL或emoji'),
    sa.Column('description', sa.Text(), nullable=True, comment='Agent描述'),
    sa.Column('system_prompt', sa.Text(), nullable=False, comment='系统提示词'),
    sa.Column('llm_config', sa.JSON(), nullable=False, comment="模型配置，如 {model: 'gpt-4o', temperature: 0.7}"),
    sa.Column('capabilities', sa.JSON(), nullable=False, comment='能力描述列表'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.CheckConstraint("role IN ('writer', 'critic', 'researcher', 'planner', 'editor', 'coder', 'designer', 'custom')", name='agents_role_check'),
    sa.PrimaryKeyConstraint('id'),
    comment='全局Agent表'
    )
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_index(op.f('ix_agents_role'), 'agents', ['role'], unique=False)
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('cover_color', sa.String(length=100), nullable=True, comment="封面渐变色，如 'from-violet-500 to-purple-600'"),
    sa.Column('tags', sa.JSON(), nullable=False, comment='项目标签列表'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='项目状态: active/paused/completed/archived'),
    sa.Column('workflow_config', sa.JSON(), nullable=False, comment='工作流配置，如自动推进设置'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed', 'archived')", name='projects_status_check'),
    sa.PrimaryKeyConstraint('id'),
    comment='项目表'
    )
    op.create_table('agent_skills',
    sa.Column('agent_id', sa.String(length=36), nullable=False, comment='关联的Agent ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='技能名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='技能描述'),
    sa.Column('skill_type', sa.String(length=50), nullable=False, comment='技能类型: prompt/template/function'),
    sa.Column('content', sa.Text(), nullable=True, comment='技能内容'),
    sa.Column('config', sa.JSON(), nullable=False, comment='技能配置'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'name', name='agent_skills_unique'),
    comment='Agent技能绑定表'
    )
    op.create_index(op.f('ix_agent_skills_agent_id'), 'agent_skills', ['agent_id'], unique=False)
    op.create_table('agent_tools',
    sa.Column('agent_id', sa.String(length=36), nullable=False, comment='关联的Agent ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='工具名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='工具描述'),
    sa.Column('tool_type', sa.String(length=50), nullable=False, comment='工具类型: builtin/function/api'),
    sa.Column('config', sa.JSON(), nullable=False, comment='工具配置'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'name', name='agent_tools_unique'),
    comment='Agent工具绑定表'
    )
    op.create_index(op.f('ix_agent_tools_agent_id'), 'agent_tools', ['agent_id'], unique=False)
    op.create_table('memories',
    sa.Column('agent_id', sa.String(length=36), nullable=False, comment='Agent ID'),
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='项目ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='笔记内容（Markdown格式）'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='内容类型'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签列表'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'project_id', name='memories_unique'),
    comment='Agent个人笔记表'
    )
    op.create_index(op.f('ix_memories_agent_id'), 'memories', ['agent_id'], unique=False)
    op.create_index(op.f('ix_memories_project_id'), 'memories', ['project_id'], unique=False)
    op.create_table('project_agents',
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='项目ID'),
    sa.Column('agent_id', sa.String(length=36), nullable=False, comment='全局Agent ID'),
    sa.Column('override_config', sa.JSON(), nullable=False, comment='项目内覆盖配置'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'agent_id', name='project_agents_unique'),
    comment='项目级Agent关联表'
    )
    op.create_index(op.f('ix_project_agents_agent_id'), 'project_agents', ['agent_id'], unique=False)
    op.create_index(op.f('ix_project_agents_project_id'), 'project_agents', ['project_id'], unique=False)
    op.create_table('tags',
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='所属项目ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='标签名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='标签说明'),
    sa.Column('suggested_template', sa.Text(), nullable=True, comment='建议的格式/模板'),
    sa.Column('color', sa.String(length=50), nullable=True, comment='标签颜色'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='tags_unique'),
    comment='项目标签表'
    )
    op.create_index(op.f('ix_tags_project_id'), 'tags', ['project_id'], unique=False)
    op.create_table('groups',
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='所属项目ID'),
    sa.Column('lead_agent_id', sa.String(length=36), nullable=True, comment='主导Agent ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='群聊名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='群聊描述'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='群聊状态: pending/active/completed'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='排序索引'),
    sa.Column('autonomy_level', sa.String(length=20), nullable=False, comment='自主级别: full_auto/semi_auto/manual'),
    sa.Column('auto_advance', sa.Boolean(), nullable=False, comment='完成后是否自动推进到下一个群聊'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.CheckConstraint("autonomy_level IN ('full_auto', 'semi_auto', 'manual')", name='groups_autonomy_check'),
    sa.CheckConstraint("status IN ('pending', 'active', 'completed')", name='groups_status_check'),
    sa.ForeignKeyConstraint(['lead_agent_id'], ['project_agents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='群聊表'
    )
    op.create_index(op.f('ix_groups_project_id'), 'groups', ['project_id'], unique=False)
    op.create_table('group_members',
    sa.Column('group_id', sa.String(length=36), nullable=False, comment='群聊ID'),
    sa.Column('project_agent_id', sa.String(length=36), nullable=False, comment='项目Agent ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='成员角色: lead/participant'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_agent_id'], ['project_agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'project_agent_id', name='group_members_unique'),
    comment='群聊成员表'
    )
    op.create_index(op.f('ix_group_members_group_id'), 'group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_members_project_agent_id'), 'group_members', ['project_agent_id'], unique=False)
    op.create_table('resources',
    sa.Column('project_id', sa.String(length=36), nullable=False, comment='所属项目ID'),
    sa.Column('group_id', sa.String(length=36), nullable=True, comment='所属群聊ID，NULL表示全局资源'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='资源标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='资源内容（Markdown格式）'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='内容类型'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='资源类型: note/reference/guideline/rule/custom'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签列表'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='是否必读'),
    sa.Column('created_by', sa.String(length=255), nullable=False, comment='创建者: user 或 agent_id'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.CheckConstraint("type IN ('note', 'reference', 'guideline', 'rule', 'custom')", name='resources_type_check'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='资源表'
    )
    op.create_index(op.f('ix_resources_group_id'), 'resources', ['group_id'], unique=False)
    op.create_index(op.f('ix_resources_project_id'), 'resources', ['project_id'], unique=False)
    op.create_table('tasks',
    sa.Column('group_id', sa.String(length=36), nullable=False, comment='所属群聊ID'),
    sa.Column('lead_agent_id', sa.String(length=36), nullable=True, comment='任务主导Agent ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='任务标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='任务描述'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='任务状态: todo/in_progress/done/reopened'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='排序索引'),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True, comment='验收标准'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='开始时间'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.CheckConstraint("status IN ('todo', 'in_progress', 'done', 'reopened')", name='tasks_status_check'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_agent_id'], ['project_agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='任务表'
    )
    op.create_index(op.f('ix_tasks_group_id'), 'tasks', ['group_id'], unique=False)
    op.create_table('chains',
    sa.Column('task_id', sa.String(length=36), nullable=False, comment='关联的任务ID'),
    sa.Column('group_id', sa.String(length=36), nullable=False, comment='所属群聊ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='链状态: active/completed'),
    sa.Column('context_snapshot', sa.JSON(), nullable=False, comment='上下文快照'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.CheckConstraint("status IN ('active', 'completed')", name='chains_status_check'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='讨论链表'
    )
    op.create_index(op.f('ix_chains_group_id'), 'chains', ['group_id'], unique=False)
    op.create_index(op.f('ix_chains_task_id'), 'chains', ['task_id'], unique=False)
    op.create_table('task_assignees',
    sa.Column('task_id', sa.String(length=36), nullable=False, comment='任务ID'),
    sa.Column('project_agent_id', sa.String(length=36), nullable=False, comment='项目Agent ID'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['project_agent_id'], ['project_agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'project_agent_id', name='task_assignees_unique'),
    comment='任务指派表'
    )
    op.create_index(op.f('ix_task_assignees_project_agent_id'), 'task_assignees', ['project_agent_id'], unique=False)
    op.create_index(op.f('ix_task_assignees_task_id'), 'task_assignees', ['task_id'], unique=False)
    op.create_table('deliverables',
    sa.Column('chain_id', sa.String(length=36), nullable=True, comment='关联的讨论链ID'),
    sa.Column('group_id', sa.String(length=36), nullable=False, comment='所属群聊ID'),
    sa.Column('task_id', sa.String(length=36), nullable=True, comment='关联的任务ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='交付物标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='交付物内容（Markdown格式）'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='内容类型'),
    sa.Column('type', sa.String(length=50), nullable=True, comment='交付物类型（标签）'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='额外标签'),
    sa.Column('author_id', sa.String(length=255), nullable=True, comment='主导Agent ID'),
    sa.Column('participant_ids', sa.JSON(), nullable=False, comment='参与Agent ID列表'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='元数据'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('scope', sa.String(length=20), nullable=False, comment='作用域: group/project'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.CheckConstraint("scope IN ('group', 'project')", name='deliverables_scope_check'),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='交付物表'
    )
    op.create_index(op.f('ix_deliverables_chain_id'), 'deliverables', ['chain_id'], unique=False)
    op.create_index(op.f('ix_deliverables_group_id'), 'deliverables', ['group_id'], unique=False)
    op.create_index(op.f('ix_deliverables_task_id'), 'deliverables', ['task_id'], unique=False)
    op.create_index(op.f('ix_deliverables_type'), 'deliverables', ['type'], unique=False)
    op.create_table('messages',
    sa.Column('chain_id', sa.String(length=36), nullable=False, comment='所属讨论链ID'),
    sa.Column('sender_id', sa.String(length=255), nullable=False, comment="发送者ID: agent_id 或 'user' 或 'system'"),
    sa.Column('sender_type', sa.String(length=20), nullable=False, comment='发送者类型: agent/user/system'),
    sa.Column('sender_name', sa.String(length=100), nullable=False, comment='发送者显示名称'),
    sa.Column('content', sa.Text(), nullable=False, comment='消息内容'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='内容类型: text/markdown/json'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='元数据'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.CheckConstraint("sender_type IN ('agent', 'user', 'system')", name='messages_sender_type_check'),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='消息表'
    )
    op.create_index(op.f('ix_messages_chain_id'), 'messages', ['chain_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('deliverable_versions',
    sa.Column('deliverable_id', sa.String(length=36), nullable=False, comment='交付物ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('content', sa.Text(), nullable=False, comment='该版本的内容'),
    sa.Column('change_summary', sa.Text(), nullable=True, comment='变更说明'),
    sa.Column('created_by', sa.String(length=255), nullable=True, comment='修改者'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.ForeignKeyConstraint(['deliverable_id'], ['deliverables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deliverable_id', 'version', name='deliverable_versions_unique'),
    comment='交付物版本表'
    )
    op.create_index(op.f('ix_deliverable_versions_deliverable_id'), 'deliverable_versions', ['deliverable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliverable_versions_deliverable_id'), table_name='deliverable_versions')
    op.drop_table('deliverable_versions')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chain_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_deliverables_type'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_task_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_group_id'), table_name='deliverables')
    op.drop_index(op.f('ix_deliverables_chain_id'), table_name='deliverables')
    op.drop_table('deliverables')
    op.drop_index(op.f('ix_task_assignees_task_id'), table_name='task_assignees')
    op.drop_index(op.f('ix_task_assignees_project_agent_id'), table_name='task_assignees')
    op.drop_table('task_assignees')
    op.drop_index(op.f('ix_chains_task_id'), table_name='chains')
    op.drop_index(op.f('ix_chains_group_id'), table_name='chains')
    op.drop_table('chains')
    op.drop_index(op.f('ix_tasks_group_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_resources_project_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_group_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_group_members_project_agent_id'), table_name='group_members')
    op.drop_index(op.f('ix_group_members_group_id'), table_name='group_members')
    op.drop_table('group_members')
    op.drop_index(op.f('ix_groups_project_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_tags_project_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_project_agents_project_id'), table_name='project_agents')
    op.drop_index(op.f('ix_project_agents_agent_id'), table_name='project_agents')
    op.drop_table('project_agents')
    op.drop_index(op.f('ix_memories_project_id'), table_name='memories')
    op.drop_index(op.f('ix_memories_agent_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_agent_tools_agent_id'), table_name='agent_tools')
    op.drop_table('agent_tools')
    op.drop_index(op.f('ix_agent_skills_agent_id'), table_name='agent_skills')
    op.drop_table('agent_skills')
    op.drop_table('projects')
    op.drop_index(op.f('ix_agents_role'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
