"""add_chain_tree_and_packet_table

Revision ID: 3b9a317d2689
Revises: d4e5f6a2b3c4
Create Date: 2026-05-23 11:54:00.202658+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b9a317d2689'
down_revision: Union[str, None] = 'd4e5f6a2b3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. 先创建 packets 表
    op.create_table('packets',
    sa.Column('chain_id', sa.String(length=36), nullable=False, comment='所属链ID'),
    sa.Column('prev_packet_id', sa.String(length=36), nullable=True, comment='链内前一个包ID（链表结构）'),
    sa.Column('packet_type', sa.String(length=20), nullable=False, comment='包类型: user_input/agent_text/think/tool_call/tool_result/error/system'),
    sa.Column('sender_type', sa.String(length=20), nullable=False, comment='发送者类型: user/agent/system/tool'),
    sa.Column('sender_id', sa.String(length=255), nullable=False, comment='发送者ID'),
    sa.Column('sender_name', sa.String(length=100), nullable=False, comment='发送者显示名称'),
    sa.Column('content', sa.Text(), nullable=False, comment='内容'),
    sa.Column('content_type', sa.String(length=20), nullable=False, comment='内容类型: text/markdown/json'),
    sa.Column('sub_chain_id', sa.String(length=36), nullable=True, comment='本包触发的子链ID'),
    sa.Column('metadata', sa.JSON(), nullable=False, comment='扩展信息（render_spec, tool_name, tool_args等）'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'),
    sa.CheckConstraint("packet_type IN ('user_input', 'agent_text', 'think', 'tool_call', 'tool_result', 'error', 'system')", name='packets_packet_type_check'),
    sa.CheckConstraint("sender_type IN ('user', 'agent', 'system', 'tool')", name='packets_sender_type_check'),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_chain_id'], ['chains.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='包表'
    )
    op.create_index(op.f('ix_packets_chain_id'), 'packets', ['chain_id'], unique=False)
    op.create_index(op.f('ix_packets_packet_type'), 'packets', ['packet_type'], unique=False)
    op.create_index(op.f('ix_packets_sender_id'), 'packets', ['sender_id'], unique=False)

    # 2. 给 chains 表添加新列（chain_type 先允许 NULL）
    op.add_column('chains', sa.Column('parent_chain_id', sa.String(length=36), nullable=True, comment='父链ID（群链为None）'))
    op.add_column('chains', sa.Column('chain_type', sa.String(length=20), nullable=True, comment='链类型: group/task/reply/tool'))
    op.add_column('chains', sa.Column('agent_id', sa.String(length=36), nullable=True, comment='执行Agent ID（reply/tool链才有）'))
    op.add_column('chains', sa.Column('head_packet_id', sa.String(length=36), nullable=True, comment='链头包ID（触发原因/请求）'))
    op.add_column('chains', sa.Column('tail_packet_id', sa.String(length=36), nullable=True, comment='链尾包ID（最终结果/回复）'))
    op.add_column('chains', sa.Column('description', sa.Text(), nullable=True, comment='描述（群链存群初始描述）'))
    op.add_column('chains', sa.Column('packet_count', sa.Integer(), nullable=True, comment='包数量（冗余缓存）'))
    op.add_column('chains', sa.Column('sub_chain_count', sa.Integer(), nullable=True, comment='子链数量（冗余缓存）'))

    # 3. 迁移现有数据：所有现有 chain 都是 task 类型
    op.execute("UPDATE chains SET chain_type = 'task', packet_count = 0, sub_chain_count = 0 WHERE chain_type IS NULL")

    # 4. 现在 chain_type 和计数字段可以设为 NOT NULL
    op.alter_column('chains', 'chain_type', nullable=False)
    op.alter_column('chains', 'packet_count', nullable=False)
    op.alter_column('chains', 'sub_chain_count', nullable=False)

    # 5. 修改现有列
    op.alter_column('chains', 'task_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True,
               comment='关联任务ID（task链才有）',
               existing_comment='关联的任务ID')
    op.alter_column('chains', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='链状态: active/completed/failed',
               existing_comment='链状态: active/completed',
               existing_nullable=False)

    # 6. 添加新的 CheckConstraint（包含 failed 状态）
    op.execute("ALTER TABLE chains DROP CONSTRAINT chains_status_check")
    op.execute("ALTER TABLE chains ADD CONSTRAINT chains_status_check CHECK (status IN ('active', 'completed', 'failed'))")

    # 7. 添加新的 CheckConstraint（chain_type）
    op.execute("ALTER TABLE chains ADD CONSTRAINT chains_chain_type_check CHECK (chain_type IN ('group', 'task', 'reply', 'tool'))")

    # 8. 更新外键和索引
    op.alter_column('chains', 'rollover_from_chain_id',
               existing_type=sa.VARCHAR(length=36),
               comment='交接来源链ID（本链由哪个链交接而来）',
               existing_comment='交接来源链ID',
               existing_nullable=True)
    op.alter_column('chains', 'rollover_summary',
               existing_type=sa.TEXT(),
               comment='交接时的总结内容（作为本链的链头上下文）',
               existing_comment='交接时的总结内容',
               existing_nullable=True)
    op.create_index(op.f('ix_chains_agent_id'), 'chains', ['agent_id'], unique=False)
    op.create_index(op.f('ix_chains_chain_type'), 'chains', ['chain_type'], unique=False)
    op.create_index(op.f('ix_chains_parent_chain_id'), 'chains', ['parent_chain_id'], unique=False)
    op.drop_constraint('chains_task_id_fkey', 'chains', type_='foreignkey')
    op.create_foreign_key(None, 'chains', 'tasks', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'chains', 'chains', ['parent_chain_id'], ['id'], ondelete='SET NULL')
    op.create_table_comment(
        'chains',
        '链表',
        existing_comment='讨论链表',
        schema=None
    )

    # 9. 删除旧列
    op.drop_column('chains', 'context_snapshot')

    # 10. 忽略无关的 comment 变更
    # agent_skills 的 comment 变更不需要执行，跳过
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chains', sa.Column('context_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False, comment='上下文快照'))
    op.create_table_comment(
        'chains',
        '讨论链表',
        existing_comment='链表',
        schema=None
    )
    op.drop_constraint(None, 'chains', type_='foreignkey')
    op.drop_constraint(None, 'chains', type_='foreignkey')
    op.create_foreign_key('chains_task_id_fkey', 'chains', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_chains_parent_chain_id'), table_name='chains')
    op.drop_index(op.f('ix_chains_chain_type'), table_name='chains')
    op.drop_index(op.f('ix_chains_agent_id'), table_name='chains')
    op.alter_column('chains', 'rollover_summary',
               existing_type=sa.TEXT(),
               comment='交接时的总结内容',
               existing_comment='交接时的总结内容（作为本链的链头上下文）',
               existing_nullable=True)
    op.alter_column('chains', 'rollover_from_chain_id',
               existing_type=sa.VARCHAR(length=36),
               comment='交接来源链ID',
               existing_comment='交接来源链ID（本链由哪个链交接而来）',
               existing_nullable=True)
    op.alter_column('chains', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='链状态: active/completed',
               existing_comment='链状态: active/completed/failed',
               existing_nullable=False)
    op.alter_column('chains', 'task_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False,
               comment='关联的任务ID',
               existing_comment='关联任务ID（task链才有）')
    op.drop_column('chains', 'sub_chain_count')
    op.drop_column('chains', 'packet_count')
    op.drop_column('chains', 'description')
    op.drop_column('chains', 'tail_packet_id')
    op.drop_column('chains', 'head_packet_id')
    op.drop_column('chains', 'agent_id')
    op.drop_column('chains', 'chain_type')
    op.drop_column('chains', 'parent_chain_id')
    op.create_table_comment(
        'agent_skills',
        'Agent技能绑定表',
        existing_comment='Agent技能关联表',
        schema=None
    )
    op.alter_column('agent_skills', 'skill_id',
               existing_type=sa.VARCHAR(length=36),
               comment='关联的技能ID',
               existing_comment='技能ID',
               existing_nullable=False)
    op.alter_column('agent_skills', 'agent_id',
               existing_type=sa.VARCHAR(length=36),
               comment='关联的Agent ID',
               existing_comment='Agent ID',
               existing_nullable=False)
    op.drop_index(op.f('ix_packets_sender_id'), table_name='packets')
    op.drop_index(op.f('ix_packets_packet_type'), table_name='packets')
    op.drop_index(op.f('ix_packets_chain_id'), table_name='packets')
    op.drop_table('packets')
    # ### end Alembic commands ###
