"""
nse_fallback_universe.py — Static top-200 NSE equities (by market cap).

Fallback used by universe.get_universe() when the live Yahoo Finance screener
returns nothing (e.g. Yahoo blocks the Hugging Face Spaces datacenter IP) and no
persistent cache is available. Keeps the top-picks scan and predictor universe
functional instead of degrading to an empty list.

Regenerate: python -c "import universe,json; json.dump(universe._fetch_nse_equity(200), open(chr(39)+'/tmp/nse200.json'+chr(39),chr(39)+'w'+chr(39)), ensure_ascii=False)"
"""

FALLBACK_UNIVERSE: dict[str, str] = {
    'RELIANCE.NS': 'Reliance Industries Limited',
    'BHARTIARTL.NS': 'Bharti Airtel Limited',
    'HDFCBANK.NS': 'HDFC Bank Limited',
    'ICICIBANK.NS': 'ICICI Bank Limited',
    'SBIN.NS': 'State Bank of India',
    'TCS.NS': 'Tata Consultancy Services Limited',
    'BAJFINANCE.NS': 'Bajaj Finance Limited',
    'LT.NS': 'Larsen & Toubro Limited',
    'HINDUNILVR.NS': 'Hindustan Unilever Limited',
    'SUNPHARMA.NS': 'Sun Pharmaceutical Industries Limited',
    'INFY.NS': 'Infosys Limited',
    'ADANIENT.NS': 'Adani Enterprises Limited',
    'ADANIPORTS.NS': 'Adani Ports and Special Economic Zone Limited',
    'MARUTI.NS': 'Maruti Suzuki India Limited',
    'ADANIPOWER.NS': 'Adani Power Limited',
    'TITAN.NS': 'Titan Company Limited',
    'AXISBANK.NS': 'Axis Bank Limited',
    'M&M.NS': 'Mahindra & Mahindra Limited',
    'KOTAKBANK.NS': 'Kotak Mahindra Bank Limited',
    'ITC.NS': 'ITC Limited',
    'ULTRACEMCO.NS': 'UltraTech Cement Limited',
    'NTPC.NS': 'NTPC Limited',
    'HCLTECH.NS': 'HCL Technologies Limited',
    'ONGC.NS': 'Oil and Natural Gas Corporation Limited',
    'JSWSTEEL.NS': 'JSW Steel Limited',
    'HAL.NS': 'Hindustan Aeronautics Limited',
    'BEL.NS': 'Bharat Electronics Limited',
    'BAJAJFINSV.NS': 'Bajaj Finserv Ltd.',
    'BAJAJ-AUTO.NS': 'Bajaj Auto Limited',
    'NESTLEIND.NS': 'Nestlé India Limited',
    'LICI.NS': 'Life Insurance Corporation of India',
    'POWERGRID.NS': 'Power Grid Corporation of India Limited',
    'ETERNAL.NS': 'Eternal Limited',
    'COALINDIA.NS': 'Coal India Limited',
    'DMART.NS': 'Avenue Supermarts Limited',
    'ASIANPAINT.NS': 'Asian Paints Limited',
    'ADANIGREEN.NS': 'Adani Green Energy Limited',
    'SHRIRAMFIN.NS': 'Shriram Finance Limited',
    'TATASTEEL.NS': 'Tata Steel Limited',
    'HINDZINC.NS': 'Hindustan Zinc Limited',
    'GRASIM.NS': 'Grasim Industries Limited',
    'HINDALCO.NS': 'Hindalco Industries Limited',
    'ADANIENSOL.NS': 'Adani Energy Solutions Limited',
    'EICHERMOT.NS': 'Eicher Motors Limited',
    'INDIGO.NS': 'InterGlobe Aviation Limited',
    'IOC.NS': 'Indian Oil Corporation Limited',
    'DIVISLAB.NS': "Divi's Laboratories Limited",
    'SBILIFE.NS': 'SBI Life Insurance Company Limited',
    'WIPRO.NS': 'Wipro Limited',
    'VAML.NS': 'Vedanta Aluminium Metal Limited',
    'SOLARINDS.NS': 'Solar Industries India Limited',
    'TVSMOTOR.NS': 'TVS Motor Company Limited',
    'TORNTPHARM.NS': 'Torrent Pharmaceuticals Limited',
    'DLF.NS': 'DLF Limited',
    'HYUNDAI.NS': 'HYUNDAI MOTOR INDIA LTD',
    'PIDILITIND.NS': 'Pidilite Industries Limited',
    'ABB.NS': 'ABB India Limited',
    'JIOFIN.NS': 'Jio Financial Services Limited',
    'VBL.NS': 'Varun Beverages Limited',
    'TRENT.NS': 'Trent Limited',
    'ICICIAMC.NS': 'ICICI PRUDENTIAL AMC LTD',
    'CUMMINSIND.NS': 'Cummins India Limited',
    'CHOLAFIN.NS': 'Cholamandalam Investment and Finance Company Limited',
    'MOTHERSON.NS': 'Samvardhana Motherson International Limited',
    'TMCV.NS': 'TATA MOTORS LIMITED',
    'BSE.NS': 'BSE Limited',
    'TATACAP.NS': 'TATA CAPITAL LIMITED',
    'IDEA.NS': 'Vodafone Idea Limited',
    'BHEL.NS': 'Bharat Heavy Electricals Limited',
    'POWERINDIA.NS': 'Hitachi Energy India Limited',
    'CGPOWER.NS': 'CG Power and Industrial Solutions Limited',
    'TECHM.NS': 'Tech Mahindra Limited',
    'PFC.NS': 'Power Finance Corporation Limited',
    'BPCL.NS': 'Bharat Petroleum Corporation Limited',
    'UNIONBANK.NS': 'Union Bank of India',
    'POLYCAB.NS': 'Polycab India Limited',
    'BANKBARODA.NS': 'Bank of Baroda Limited',
    'BRITANNIA.NS': 'Britannia Industries Limited',
    'SIEMENS.NS': 'Siemens Limited',
    'PNB.NS': 'Punjab National Bank',
    'APOLLOHOSP.NS': 'Apollo Hospitals Enterprise Limited',
    'GROWW.NS': 'BILLIONBRAINS GARAGE VN L',
    'TMPV.NS': 'Tata Motors Passenger Vehicles Limited',
    'TATAPOWER.NS': 'The Tata Power Company Limited',
    'HDFCLIFE.NS': 'HDFC Life Insurance Company Limited',
    'ENRIN.NS': 'Siemens Energy India Limited',
    'LTM.NS': 'LTM Limited',
    'BOSCHLTD.NS': 'Bosch Limited',
    'MUTHOOTFIN.NS': 'Muthoot Finance Limited',
    'LODHA.NS': 'Lodha Developers Limited',
    'GMRAIRPORT.NS': 'GMR Airports Limited',
    'CIPLA.NS': 'Cipla Limited',
    'CANBK.NS': 'Canara Bank',
    'IRFC.NS': 'Indian Railway Finance Corporation Limited',
    'ZYDUSLIFE.NS': 'Zydus Lifesciences Limited',
    'INDIANB.NS': 'Indian Bank',
    'BAJAJHLDNG.NS': 'Bajaj Holdings & Investment Limited',
    'GVT&D.NS': 'GE Vernova T&D India Ltd',
    'GAIL.NS': 'GAIL (India) Limited',
    'LUPIN.NS': 'Lupin Limited',
    'HDFCAMC.NS': 'HDFC Asset Management Company Limited',
    'MARICO.NS': 'Marico Limited',
    'ABCAPITAL.NS': 'Aditya Birla Capital Limited',
    'AMBUJACEM.NS': 'Ambuja Cements Limited',
    'GODREJCP.NS': 'Godrej Consumer Products Limited',
    'TATACONSUM.NS': 'Tata Consumer Products Limited',
    'MAXHEALTH.NS': 'Max Healthcare Institute Limited',
    'LGEINDIA.NS': 'LG ELECTRONICS INDIA LTD',
    'INDUSTOWER.NS': 'Indus Towers Limited',
    'MANKIND.NS': 'Mankind Pharma Limited',
    'LLOYDSME.NS': 'Lloyds Metals and Energy Limited',
    'BHARATFORG.NS': 'Bharat Forge Limited',
    'JINDALSTEL.NS': 'Jindal Steel Limited',
    'JSWENERGY.NS': 'JSW Energy Limited',
    'INDHOTEL.NS': 'The Indian Hotels Company Limited',
    'DRREDDY.NS': "Dr. Reddy's Laboratories Limited",
    'VEDL.NS': 'Vedanta Limited',
    'OFSS.NS': 'Oracle Financial Services Software Limited',
    'HEROMOTOCO.NS': 'Hero MotoCorp Limited',
    'UNITDSPR.NS': 'UNITED SPIRITS LIMITED',
    'SHREECEM.NS': 'Shree Cement Limited',
    'RECLTD.NS': 'REC Limited',
    'MAZDOCK.NS': 'Mazagon Dock Shipbuilders Limited',
    'LENSKART.NS': 'LENSKART SOLUTIONS LTD',
    'NYKAA.NS': 'FSN E-Commerce Ventures Limited',
    'IDBI.NS': 'IDBI Bank Limited',
    'ASHOKLEY.NS': 'Ashok Leyland Limited',
    'AUROPHARMA.NS': 'Aurobindo Pharma Limited',
    'DIXON.NS': 'Dixon Technologies (India) Limited',
    'MEESHO.NS': 'MEESHO LIMITED',
    'FEDERALBNK.NS': 'The Federal Bank Limited',
    'PAYTM.NS': 'One97 Communications Limited',
    'HINDPETRO.NS': 'Hindustan Petroleum Corporation Limited',
    'SRF.NS': 'SRF Limited',
    'LAURUSLABS.NS': 'Laurus Labs Limited',
    'WAAREEENER.NS': 'WAAREE ENERGIES LIMITED',
    'NHPC.NS': 'NHPC Limited',
    'BHARTIHEXA.NS': 'BHARTI HEXACOM LIMITED',
    'ICICIGI.NS': 'ICICI Lombard General Insurance Company Limited',
    'PERSISTENT.NS': 'Persistent Systems Limited',
    'JSWINFRA.NS': 'JSW Infrastructure Limited',
    'INDUSINDBK.NS': 'IndusInd Bank Limited',
    'ATGL.NS': 'Adani Total Gas Limited',
    'NTPCGREEN.NS': 'NTPC GREEN ENERGY LIMITED',
    'NAUKRI.NS': 'Info Edge (India) Limited',
    'LTF.NS': 'L&T Finance Limited',
    'NAM-INDIA.NS': 'Nippon Life India Asset Management Limited',
    'DABUR.NS': 'Dabur India Limited',
    'HAVELLS.NS': 'Havells India Limited',
    'AUBANK.NS': 'AU Small Finance Bank Limited',
    'PHOENIXLTD.NS': 'The Phoenix Mills Limited',
    'NMDC.NS': 'NMDC Limited',
    'OIL.NS': 'Oil India Limited',
    'POLICYBZR.NS': 'PB Fintech Limited',
    'SUZLON.NS': 'Suzlon Energy Limited',
    'TORNTPOWER.NS': 'Torrent Power Limited',
    'FORTIS.NS': 'Fortis Healthcare Limited',
    'YESBANK.NS': 'Yes Bank Limited',
    'ICICIPRULI.NS': 'ICICI Prudential Life Insurance Company Limited',
    'MCX.NS': 'Multi Commodity Exchange of India Limited',
    'PRESTIGE.NS': 'Prestige Estates Projects Limited',
    'BAJAJHFL.NS': 'BAJAJ HOUSING FINANCE LTD',
    'BIOCON.NS': 'Biocon Limited',
    'ASTERDM.NS': 'Aster DM Quality Care Limited',
    'SWIGGY.NS': 'SWIGGY LIMITED',
    'IDFCFIRSTB.NS': 'IDFC First Bank Limited',
    'OBEROIRLTY.NS': 'Oberoi Realty Limited',
    'ALKEM.NS': 'Alkem Laboratories Limited',
    'SAIL.NS': 'Steel Authority of India Limited',
    'IOB.NS': 'Indian Overseas Bank',
    'BANKINDIA.NS': 'Bank of India Limited',
    'UNOMINDA.NS': 'Uno Minda Limited',
    'COFORGE.NS': 'Coforge Limited',
    'SCHAEFFLER.NS': 'Schaeffler India Limited',
    'GLENMARK.NS': 'Glenmark Pharmaceuticals Limited',
    'GICRE.NS': 'General Insurance Corporation of India',
    'GODREJPROP.NS': 'Godrej Properties Limited',
    'NATIONALUM.NS': 'National Aluminium Company Limited',
    'SBICARD.NS': 'SBI Cards and Payment Services Limited',
    'MAHABANK.NS': 'Bank of Maharashtra',
    'JSL.NS': 'Jindal Stainless Limited',
    'ABBOTINDIA.NS': 'Abbott India Limited',
    'HDBFS.NS': 'HDB FINANCIAL SERVICES L',
    'COROMANDEL.NS': 'Coromandel International Limited',
    'LINDEINDIA.NS': 'Linde India Limited',
    'MOTILALOFS.NS': 'Motilal Oswal Financial Services Limited',
    'KALYANKJIL.NS': 'Kalyan Jewellers India Limited',
    'RBLBANK.NS': 'RBL Bank Limited',
    'COLPAL.NS': 'Colgate-Palmolive (India) Limited',
    'BERGEPAINT.NS': 'Berger Paints India Limited',
    'MRF.NS': 'MRF Limited',
    'TIINDIA.NS': 'Tube Investments of India Limited',
    'APARINDS.NS': 'APAR Industries Limited',
    'RADICO.NS': 'Radico Khaitan Limited',
    'FACT.NS': 'The Fertilisers and Chemicals Travancore Limited',
    'THERMAX.NS': 'Thermax Limited',
    'MFSL.NS': 'Max Financial Services Limited',
    'VMM.NS': 'VISHAL MEGA MART LIMITED',
    'TATACOMM.NS': 'Tata Communications Limited',
    'UPL.NS': 'UPL Limited',
}
