token: "YOUR_LICHESS_TOKEN" 
url: "https://lichess.org/"

engine:
  dir: "./engines/"
  protocol: "homemade"
  name: "MultiEngineRouter"
  ponder: true
  debug: true 
  online_moves:
    online_egtb:
      enabled: false

correspondence:
  move_time: 10
  checkin_period: 5
  disconnect_time: 300
  ponder: true

challenge:
  concurrency: 1
  sort_by: "best"
  accept_bot: true
  only_bot: false
  min_base: 60
  max_base: 1800
  # 以下是新增的必须字段 👇
  variants:
    - standard
    - fromPosition
    - antichess
    - atomic
    - chess960
    - crazyhouse
    - horde
    - kingOfTheHill
    - racingKings
    - threeCheck
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
    - correspondence
  modes:
    - casual

greeting:
  hello: Hello {opponent}! I hope this will be an equal game. Type !help for a list of command I can respond to.
  goodbye: Good game!
  hello_spectators: No way you came to watch my game. Wow! Type !help for a list of command I can respond to.
  goodbye_spectators: Thanks for watching!

matchmaking:
  allow_matchmaking: true
  allow_during_games: false
  challenge_timeout: 20
  challenge_variant: "random"
  challenge_initial_time:
    - 600
    - 300
    - 900
    - 180
  challenge_increment:
    - 0
    - 2
    - 3
    - 5
  challenge_mode: casual
  challenge_filter: fine