dataset: ruler
data_dir: 4096
model: Qwen/Qwen3-8B
device: cuda:0
press_name: RestoreKV_plus
compression_ratio: 0.25
key_channel_compression_ratio: null
restore_checkpoint: higokri/RestoreKV/qwen3-8b_restorekv_plus.pt
fraction: 1.0
max_new_tokens: null
max_context_length: null
query_aware: false
needle_depth: null
compression_interval: null
target_size: null
hidden_states_buffer_size: null
output_dir: ./results_lb
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
press_init_command: RestoreKVPress(compression_ratio=0.25, layerwise=False, n_sink=4,
  kvzip_plus_normalization=True, checkpoint_path='higokri/RestoreKV/qwen3-8b_restorekv_plus.pt',
  budget_matched=True)
seed: 42
fp8: false
