dataset: ruler
data_dir: 4096
model: Qwen/Qwen3-8B
device: cuda:3
press_name: kvzap_linear
compression_ratio: 0.5
key_channel_compression_ratio: null
threshold: -6
fraction: 1.0
max_new_tokens: null
max_context_length: null
compress_questions: false
needle_depth: null
compression_interval: null
target_size: null
hidden_states_buffer_size: null
output_dir: ./results_lb
log_level: INFO
model_kwargs:
  attn_implementation: flash_attention_2
  dtype: auto
press_init_command:
  DMSPress(press=KVzapPress(compression_ratio=0.0, model_type='linear',
  kvzap_model_name=None), threshold=-6, sliding_window_size=128, decoding=False)
seed: 42
