@echo off
cd /d "%~dp0"
echo Installing requirements...
pip install -r requirements.txt
echo Running model training...
python ..\model\train_model.py
echo Verifying model...
python verify_model.py
echo DONE!
