from __future__ import annotations

import html
import json
import os
import shutil
from typing import Any, Dict, List

from . import cost as cost_mod
from .models import CONFIRMED, DISPUTED, REJECTED, REPRODUCED, BugResult, dumps
from .trial import SuiteResult, metrics

PUBLISHED_TRIALS_PER_BUG = 1

PAGE = """<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>ARBITER results</title>
<style>
 :root{--bg:#0f1319;--card:#161c25;--line:#242e3b;--fg:#e6eaf0;--muted:#94a3b8;
       --good:#34d399;--bad:#f87171;--warn:#fbbf24;--accent:#60a5fa}
 *{box-sizing:border-box}
 body{margin:0;background:var(--bg);color:var(--fg);
      font:15px/1.6 ui-sans-serif,system-ui,Segoe UI,Roboto,sans-serif}
 .wrap{max-width:1080px;margin:0 auto;padding:32px 20px 80px}
 h1{margin:0 0 4px;font-size:28px;letter-spacing:-.02em}
 h2{margin:36px 0 12px;font-size:19px}
 .sub{color:var(--muted);margin-bottom:24px}
 .cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}
 .card{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:14px 16px}
 .card .v{font-size:26px;font-weight:650;letter-spacing:-.02em}
 .card .k{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.06em}
 table{width:100%;border-collapse:collapse;background:var(--card);
       border:1px solid var(--line);border-radius:10px;overflow:hidden;font-size:14px}
 th,td{padding:10px 12px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}
 th{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.05em}
 tr:last-child td{border-bottom:none}
 .pill{display:inline-block;padding:2px 8px;border-radius:99px;font-size:12px;font-weight:600}
 .ok{background:rgba(52,211,153,.15);color:var(--good)}
 .no{background:rgba(248,113,113,.15);color:var(--bad)}
 .mid{background:rgba(251,191,36,.15);color:var(--warn)}
 .bar{height:6px;background:#22303f;border-radius:99px;overflow:hidden;min-width:70px}
 .bar i{display:block;height:100%;background:var(--accent)}
 details{background:var(--card);border:1px solid var(--line);border-radius:10px;
         padding:12px 16px;margin-bottom:10px}
 summary{cursor:pointer;font-weight:600}
 .trial{border-left:2px solid var(--line);padding:8px 0 8px 14px;margin:12px 0}
 .muted{color:var(--muted)}
 code{background:#0b0f14;padding:1px 5px;border-radius:4px;font-size:13px}
 .shots{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}
 .shots img{width:210px;border:1px solid var(--line);border-radius:6px}
 .sig{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;color:var(--muted)}
 footer{margin-top:48px;color:var(--muted);font-size:13px}
</style></head><body><div class="wrap">
<h1>ARBITER</h1>
<div class="sub">Automated Reproduction of Bugs with Independent Trial Evidence Review<br>
run %%STARTED%% | actor <code>%%ACTOR%%</code> | judge <code>%%JUDGE%%</code>
| %%TRIALS%% trial(s) per report | %%DURATION%%s</div>
%%CARDS%%
<h2>Per report</h2>
%%TABLE%%
<h2>Evidence</h2>
%%DETAILS%%
<footer>Generated by <code>arbiter report</code>. Every number here is derived from
<code>results.json</code> in this directory. A trial counts as a reproduction only when the
independent judge confirms the actor's claim from the evidence.</footer>
</div></body></html>"""


def _pill(text: str, kind: str) -> str:
    return '<span class="pill {0}">{1}</span>'.format(kind, html.escape(text))


def _verdict_pill(r: BugResult) -> str:
    if r.spec.control:
        return _pill("no bug found", "ok") if r.verdict != REPRODUCED else _pill("FALSE POSITIVE", "no")
    return _pill("reproduced", "ok") if r.verdict == REPRODUCED else _pill("not reproduced", "no")


def _cards(m: Dict[str, Any]) -> str:
    items = [
        ("{0}/{1}".format(m["reproduced"], m["seeded_bugs"]), "seeded bugs reproduced"),
        ("{0:.0%}".format(m["reproduction_rate"]), "reproduction rate"),
        ("{0}/{1}".format(m["false_positives"], m["controls"]), "false positives on controls"),
        ("{0:.0%}".format(m["accuracy"]), "overall accuracy"),
        ("{0} -> {1}".format(m["actor_claimed"], m["judge_confirmed"]), "actor claims vs judge confirms"),
        ("{0:.0%}".format(m["overclaim_rate"]), "claims rejected by judge"),
        ("{0}".format(m["cost"]["calls"]), "model calls"),
        ("${0:.4f}".format(m["cost"]["usd"]), "total cost"),
    ]
    return '<div class="cards">' + "".join(
        '<div class="card"><div class="v">{0}</div><div class="k">{1}</div></div>'.format(
            html.escape(v), html.escape(k)) for v, k in items) + "</div>"


def _table(suite: SuiteResult) -> str:
    rows = []
    for r in suite.results:
        usages = [u for t in r.trials for u in (t.actor_usage, t.judge_usage)]
        rows.append(
            "<tr><td><code>{id}</code></td><td>{cat}</td><td>{truth}</td><td>{verdict}</td>"
            '<td><div class="bar"><i style="width:{pct}%"></i></div>'
            '<span class="muted">{conf}/{n} trials</span></td>'
            "<td>{stab}</td><td>{claims}</td><td>${cost:.4f}</td></tr>".format(
                id=html.escape(r.spec.id), cat=html.escape(r.spec.category),
                truth="seeded bug" if not r.spec.control else "control (no bug)",
                verdict=_verdict_pill(r), pct=int(round(r.reproduction_rate * 100)),
                conf=r.confirmed, n=len(r.trials), stab=r.stability,
                claims="{0} claimed / {1} confirmed".format(r.actor_claimed, r.confirmed),
                cost=cost_mod.total(usages)))
    return ("<table><tr><th>report</th><th>category</th><th>ground truth</th><th>verdict</th>"
            "<th>reproduction rate</th><th>stability</th><th>actor vs judge</th><th>cost</th></tr>"
            + "".join(rows) + "</table>")


def _details(suite: SuiteResult, out_dir: str) -> str:
    blocks = []
    for r in suite.results:
        trials_html = []
        for t in r.trials:
            shots = []
            if t.trial_index < PUBLISHED_TRIALS_PER_BUG:
                rel_dir = os.path.join("evidence", r.spec.id, "t{0}".format(t.trial_index))
                abs_dir = os.path.join(out_dir, rel_dir)
                os.makedirs(abs_dir, exist_ok=True)
                from .judge import select_evidence_images
                paths, notes = select_evidence_images(t.steps, t.evidence_dir)
                for p, note in zip(paths, notes):
                    name = os.path.basename(p)
                    try:
                        shutil.copyfile(p, os.path.join(abs_dir, name))
                    except OSError:
                        continue
                    shots.append('<figure style="margin:0"><img src="{0}" alt="{1}">'
                                 '<figcaption class="muted" style="font-size:12px;max-width:210px">'
                                 "{1}</figcaption></figure>".format(
                                     html.escape(os.path.join(rel_dir, name).replace("\\", "/")),
                                     html.escape(note)))
            hard = [s for s in t.signals if s.severity == "hard"]
            outcome_class = {CONFIRMED: "ok", REJECTED: "no", DISPUTED: "mid"}.get(t.outcome, "mid")
            trials_html.append(
                '<div class="trial"><div>{0} | {1} step(s) | {2:.0f}s</div>'
                '<div class="muted">actor said <b>{3}</b>: {4}</div>'
                '<div class="muted">judge said <b>{5}</b> (confidence {6:.2f}): {7}</div>'
                '<div class="sig">{8}</div>{9}</div>'.format(
                    _pill(t.outcome.replace("_", " ").lower(), outcome_class),
                    len(t.steps), t.duration_s,
                    html.escape(t.actor_verdict), html.escape(t.actor_reason[:400]),
                    html.escape(t.judge_verdict), t.judge_confidence,
                    html.escape(t.judge_reason[:400]),
                    html.escape(" | ".join(s.line() for s in hard)[:500]) or
                    '<span class="muted">no hard signals</span>',
                    '<div class="shots">{0}</div>'.format("".join(shots)) if shots else ""))
        blocks.append(
            "<details><summary>{0}: {1}</summary>"
            '<p class="muted">{2}</p><pre class="sig" style="white-space:pre-wrap">{3}</pre>{4}</details>'.format(
                html.escape(r.spec.id), html.escape(r.spec.title),
                html.escape(r.spec.pattern), html.escape(r.spec.report.strip()[:900]),
                "".join(trials_html)))
    return "".join(blocks)


def write_report(suite: SuiteResult, out_dir: str) -> Dict[str, str]:
    os.makedirs(out_dir, exist_ok=True)
    m = metrics(suite)

    payload = {"config": suite.config, "started_at": suite.started_at,
               "finished_at": suite.finished_at, "metrics": m,
               "bugs": [{
                   "id": r.spec.id, "title": r.spec.title, "category": r.spec.category,
                   "control": r.spec.control, "ground_truth": r.spec.ground_truth,
                   "verdict": r.verdict, "correct": r.correct,
                   "reproduction_rate": r.reproduction_rate, "stability": r.stability,
                   "actor_claimed": r.actor_claimed, "judge_confirmed": r.confirmed,
                   "judge_rejected": r.rejected, "judge_disputed": r.disputed,
                   "trials": [json.loads(dumps(t)) for t in r.trials],
               } for r in suite.results]}
    json_path = os.path.join(out_dir, "results.json")
    with open(json_path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, default=str)

    html_path = os.path.join(out_dir, "index.html")
    with open(html_path, "w", encoding="utf-8") as fh:
        page = PAGE
        for token, value in (
            ("%%STARTED%%", html.escape(suite.started_at)),
            ("%%ACTOR%%", html.escape(str(suite.config.get("actor")))),
            ("%%JUDGE%%", html.escape(str(suite.config.get("judge")))),
            ("%%TRIALS%%", str(suite.config.get("trials_per_bug"))),
            ("%%DURATION%%", str(suite.duration_s)),
            ("%%CARDS%%", _cards(m)),
            ("%%TABLE%%", _table(suite)),
            ("%%DETAILS%%", _details(suite, out_dir)),
        ):
            page = page.replace(token, value)
        fh.write(page)

    md_path = os.path.join(out_dir, "summary.md")
    with open(md_path, "w", encoding="utf-8") as fh:
        fh.write(markdown_summary(suite, m))
    return {"json": json_path, "html": html_path, "markdown": md_path}


def markdown_summary(suite: SuiteResult, m: Dict[str, Any]) -> str:
    lines = [
        "## Results", "",
        "| metric | value |", "|---|---|",
        "| seeded bugs reproduced | {0} / {1} ({2:.0%}) |".format(
            m["reproduced"], m["seeded_bugs"], m["reproduction_rate"]),
        "| false positives on controls | {0} / {1} |".format(m["false_positives"], m["controls"]),
        "| overall accuracy | {0:.0%} |".format(m["accuracy"]),
        "| trials run | {0} |".format(m["trials_total"]),
        "| actor claimed reproduction | {0} trials |".format(m["actor_claimed"]),
        "| judge confirmed | {0} trials |".format(m["judge_confirmed"]),
        "| judge rejected the actor's claim | {0} trials ({1:.0%} of claims) |".format(
            m["judge_rejected"], m["overclaim_rate"]),
        "| judge overruled a negative actor | {0} trials |".format(m["judge_disputed"]),
        "| model calls | {0} |".format(m["cost"]["calls"]),
        "| tokens in / out | {0:,} / {1:,} |".format(
            m["cost"]["prompt_tokens"], m["cost"]["completion_tokens"]),
        "| cost at paid-tier rates | ${0:.4f} |".format(m["cost"]["usd"]),
        "| wall clock | {0:.0f}s |".format(m["duration_s"]),
        "", "### Per report", "",
        "| report | category | ground truth | verdict | reproduction rate | stability |",
        "|---|---|---|---|---|---|",
    ]
    for r in suite.results:
        lines.append("| `{0}` | {1} | {2} | {3} | {4}/{5} | {6} |".format(
            r.spec.id, r.spec.category,
            "seeded bug" if not r.spec.control else "control",
            r.verdict.lower().replace("_", " "), r.confirmed, len(r.trials), r.stability))
    return "\n".join(lines) + "\n"
