# -*- coding: ascii -*-
"""
gedcom_to_prolog.py -- Compile parsed GEDCOM into a Prolog fact base.

MemorialWiki-4C, module M1b.  Layer: K1 (structured genealogy) -> V (verifier).

Emitted predicates (all facts, all ground):
    person(Id).
    person_name(Id, Name).            % quoted atom
    sex(Id, m | f | u).
    birth(Id, date(Y, M, D)).         % components: integer | unknown
    death(Id, date(Y, M, D)).
    approx_date(Id, birth | death).   % qualifier was ABT/EST/CAL/BEF/AFT/BET
    family(Fid).
    husband(Fid, Id).
    wife(Fid, Id).
    child_in(Id, Fid).
    marriage(Fid, date(Y, M, D)).
    approx_marriage(Fid).
    parse_issue(Msg).                 % structural problems from the parser

Design rule: the compiler NEVER invents data.  A missing component is the
atom 'unknown', and the rule base treats unknowns conservatively (a check
that cannot be decided yields no finding; completeness gaps are reported
separately as C4 output, never as C1 violations).

ASCII-only. Python 3.10, conda env: llmwiki.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from gedcom_parser import parse_gedcom  # noqa: E402


def q(atom_text):
    """Render text as a quoted Prolog atom, escaping backslash and quote."""
    if atom_text is None:
        return "unknown"
    s = str(atom_text).replace("\\", "\\\\").replace("'", "\\'")
    return "'%s'" % s


def date_term(d):
    """Render a partial-date dict as date(Y, M, D) with unknowns."""
    if d is None:
        return None
    parts = []
    for k in ("year", "month", "day"):
        v = d.get(k)
        parts.append(str(v) if isinstance(v, int) else "unknown")
    if parts == ["unknown", "unknown", "unknown"]:
        return None  # fully unknown date: emit nothing, C4 will flag the gap
    return "date(%s, %s, %s)" % tuple(parts)


def compile_gedcom(gedcom_path, out_path):
    """Compile a GEDCOM file into a Prolog fact file. Returns stats dict."""
    individuals, families, issues = parse_gedcom(gedcom_path)
    lines = []
    add = lines.append

    add("%% Auto-generated by gedcom_to_prolog.py -- do not edit by hand.")
    add("%% Source: %s" % os.path.basename(gedcom_path))
    add(":- discontiguous person/1, person_name/2, sex/2, birth/2,")
    add("   death/2, approx_date/2, family/1, husband/2, wife/2,")
    add("   child_in/2, marriage/2, approx_marriage/1, parse_issue/1.")
    add("")

    for pid in sorted(individuals):
        ind = individuals[pid]
        add("person(%s)." % q(pid))
        if ind["name"]:
            add("person_name(%s, %s)." % (q(pid), q(ind["name"])))
        if ind["sex"]:
            add("sex(%s, %s)." % (q(pid), ind["sex"]))
        for ev in ("birth", "death"):
            dt = date_term(ind[ev])
            if dt:
                add("%s(%s, %s)." % (ev, q(pid), dt))
                if ind[ev].get("qual"):
                    add("approx_date(%s, %s)." % (q(pid), ev))
        add("")

    for fid in sorted(families):
        fam = families[fid]
        add("family(%s)." % q(fid))
        if fam["husb"]:
            add("husband(%s, %s)." % (q(fid), q(fam["husb"])))
        if fam["wife"]:
            add("wife(%s, %s)." % (q(fid), q(fam["wife"])))
        for cid in fam["chil"]:
            add("child_in(%s, %s)." % (q(cid), q(fid)))
        if fam["marr"]:
            dt = date_term(fam["marr"])
            if dt:
                add("marriage(%s, %s)." % (q(fid), dt))
                if fam["marr"].get("qual"):
                    add("approx_marriage(%s)." % q(fid))
        add("")

    for msg in issues:
        add("parse_issue(%s)." % q(msg))

    with open(out_path, "w", encoding="ascii", errors="replace") as f:
        f.write("\n".join(lines) + "\n")

    return {
        "individuals": len(individuals),
        "families": len(families),
        "parse_issues": len(issues),
        "facts_file": out_path,
    }


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: python gedcom_to_prolog.py <input.ged> [output.pl]")
        sys.exit(1)
    src = sys.argv[1]
    dst = sys.argv[2] if len(sys.argv) > 2 else "facts.pl"
    stats = compile_gedcom(src, dst)
    print("Compiled %(individuals)d individuals, %(families)d families "
          "(%(parse_issues)d parse issues) -> %(facts_file)s" % stats)
